FROM httpd
MAINTAINER hardikgw@gmail.com
RUN apt-get update && apt-get install -y openssh-server monit
RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

RUN touch start.sh &&\
	echo "#!/usr/bin/env bash" >> start.sh &&\
	echo "monit -I" >> start.sh &&\
	chmod 755 start.sh

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]