FROM ubuntu:16.04
MAINTAINER hardikgw@gmail.com
RUN apt-get update
RUN apt-get install -y vim curl wget
RUN apt-get update && \
    apt-get install --no-install-recommends -y software-properties-common && \
    apt-add-repository ppa:ansible/ansible && \
    apt-get update && \
    apt-get install -y ansible