FROM 1213-domain
MAINTAINER hardikgw@gmail.com
USER root
RUN ssh-keygen -A
RUN echo 'root:root' | chpasswd

RUN touch start.sh &&\
	echo "#!/usr/bin/env bash" >> /start.sh &&\
	echo "/usr/sbin/sshd" &&\
	echo "./startWebLogic.sh" >> start.sh &&\
	chmod 755 start.sh
CMD ./start.sh
EXPOSE 22