version: '2'
services:
  web1:
    container_name: web1
    user: root
    build:
      context: .
      dockerfile: Dockerfile-wl
    tty: false
    ports:
      - "3122:22"
      - "3180:80"
      - "8101:8001"
    extra_hosts:
      - "mysql:172.16.239.13"
    networks:
      ansible_net:
        ipv4_address: 172.16.239.11
  web2:
    container_name: web2
    user: root
    build:
      context: .
      dockerfile: Dockerfile-wl
    ports:
      - "3222:22"
      - "3280:80"
      - "8201:8001"
    extra_hosts:
      - "mysql:172.16.239.13"
    networks:
      ansible_net:
        ipv4_address: 172.16.239.12
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    extra_hosts:
      - "web1:172.16.239.11"
      - "web2:172.16.239.12"
    networks:
      ansible_net:
        ipv4_address: 172.16.239.13
  ansible:
    container_name: ansible
    depends_on:
      - web1
      - web2
    build:
      context: .
      dockerfile: Dockerfile-ansible
    extra_hosts:
      - "web1:172.16.239.11"
      - "web2:172.16.239.12"
    command: ./start.sh
    networks:
      ansible_net:
        ipv4_address: 172.16.239.16
networks:
  ansible_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
        gateway: 172.16.239.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1

