---
- hosts: webservers
  become: yes
  become_user: oracle
  become_method: su
  gather_facts: yes
  remote_user: root
  tasks:
    - name: change weblogic datasource password
      become: yes
      become_user: oracle
      shell: source ~/.bashrc && wlst /wl-change-pswd.py newpassword