FROM cithub/ansible
MAINTAINER hardikgw@gmail.com
COPY conf/ansible_hosts /etc/ansible/hosts
COPY conf/ansible.cfg /etc/ansible/ansible.cfg
COPY conf/automate.yml /automate.yml
COPY conf/ping.yml /ping.yml
