---

- hosts: webservers
  remote_user: root
  tasks:
    - name: check all status
      include: status.yml
      register: listener_status
    - debug: msg="{{listener_status}}"

- hosts: web1
  remote_user: root
  tasks:
    - name: start primary if down
      include: start.yml
      when: hostvars.web1.listener_status.content != "ok"
    - debug: msg="{{hostvars.web1.listener_status.content}}"

    - name: update primary status
      include: status.yml
      register: listener_status
    - debug: msg="{{listener_status}}"

- hosts: web2
  remote_user: root
  tasks:
    - name: start secondary if primary is down
      include: start.yml
      when: hostvars.web1.listener_status.content != "ok"
    - debug: msg="{{hostvars.web1.listener_status.content}}"

    - name: stop secondary if primary is up
      include: stop.yml
      when: hostvars.web1.listener_status.content == "ok"
    - debug: msg="{{hostvars.web1.listener_status.content}}"
