---
- hosts: mq:mq
  vars:
    max_clients: 200
  remote_user: admin
  tasks:
    - name: mq connection
      ping:
      remote_user: admin
- hosts: webservers
  vars:
    max_clients: 200
  remote_user: root
  tasks:
    - name: web connection
      ping:
      remote_user: root